apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: ks-dev-test
  name: ks-dev-test
  namespace: kubesphere-sample-dev
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30862
  selector:
    app: kubesphere
    component: ks-dev-test
    tier: backend
  sessionAffinity: None
  type: NodePort
